{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "512aee58-f27b-4494-8bd8-8072e534e69c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: xgboost in c:\\users\\vetdd\\anaconda3\\lib\\site-packages (3.0.0)\n",
      "Requirement already satisfied: numpy in c:\\users\\vetdd\\anaconda3\\lib\\site-packages (from xgboost) (1.26.4)\n",
      "Requirement already satisfied: scipy in c:\\users\\vetdd\\anaconda3\\lib\\site-packages (from xgboost) (1.13.1)\n"
     ]
    }
   ],
   "source": [
    "!pip install xgboost\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "728015b0-8d54-477c-a9e3-ba1f11eb7fd5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded data from CSV: C:\\Users\\vetdd\\Documents\\NSS_project\\BreastCancerAIProject\\notebook\\data\\bcsc_concatenated_no_hist9.csv\n",
      "Dropped column: count\n",
      "Dropped column: year\n",
      "Filtered out 0 rows with breast_cancer_history == 9.\n",
      "Training shape: (953150, 10), Test shape: (238288, 10)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\vetdd\\anaconda3\\Lib\\site-packages\\xgboost\\training.py:183: UserWarning: [00:35:21] WARNING: C:\\actions-runner\\_work\\xgboost\\xgboost\\src\\learner.cc:738: \n",
      "Parameters: { \"use_label_encoder\" } are not used.\n",
      "\n",
      "  bst.update(dtrain, iteration=i, fobj=obj)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model training finished.\n",
      "Classification Report:\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.84      0.97      0.90    193933\n",
      "           1       0.62      0.19      0.29     44355\n",
      "\n",
      "    accuracy                           0.83    238288\n",
      "   macro avg       0.73      0.58      0.60    238288\n",
      "weighted avg       0.80      0.83      0.79    238288\n",
      "\n",
      "ROC AUC: 0.8283\n",
      "Saved model to C:\\Users\\vetdd\\Documents\\NSS_project\\BreastCancerAIProject\\notebook\\data\\bcsc_xgb_model.pkl\n",
      "Saved feature encoders to C:\\Users\\vetdd\\Documents\\NSS_project\\BreastCancerAIProject\\notebook\\data\\bcsc_feature_encoders.pkl\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import classification_report, roc_auc_score\n",
    "import xgboost as xgb\n",
    "import joblib\n",
    "\n",
    "DATA_DIR = os.path.join(os.getcwd(), \"data\")  # e.g., \"C:/Users/vetdd/Documents/NSS_project/BreastCancerAIProject/data\"\n",
    "FILENAME_CSV = \"bcsc_concatenated_no_hist9.csv\"\n",
    "FILENAME_XLSX = \"bcsc_concatenated_no_hist9.xlsx\"\n",
    "csv_path = os.path.join(DATA_DIR, FILENAME_CSV)\n",
    "xlsx_path = os.path.join(DATA_DIR, FILENAME_XLSX)\n",
    "\n",
    "# 3. Check which file exists and load accordingly\n",
    "if os.path.exists(csv_path):\n",
    "    df = pd.read_csv(csv_path)\n",
    "    print(f\"Loaded data from CSV: {csv_path}\")\n",
    "elif os.path.exists(xlsx_path):\n",
    "    df = pd.read_excel(xlsx_path)\n",
    "    print(f\"Loaded data from Excel: {xlsx_path}\")\n",
    "else:\n",
    "    raise FileNotFoundError(\n",
    "        f\"Neither '{FILENAME_CSV}' nor '{FILENAME_XLSX}' found in '{DATA_DIR}'\"\n",
    "    )\n",
    "\n",
    "# 3) Drop unwanted columns if present\n",
    "for c in [\"count\", \"year\"]:\n",
    "    if c in df.columns:\n",
    "        df.drop(columns=[c], inplace=True)\n",
    "        print(f\"Dropped column: {c}\")\n",
    "\n",
    "# 4) Filter out 'Unknown' target values -> breast_cancer_history == 9\n",
    "if 'breast_cancer_history' not in df.columns:\n",
    "    raise KeyError(\"Target column 'breast_cancer_history' not found.\")\n",
    "initial_count = df.shape[0]\n",
    "df = df[df['breast_cancer_history'] != 9].reset_index(drop=True)\n",
    "filtered_count = df.shape[0]\n",
    "print(f\"Filtered out {initial_count - filtered_count} rows with breast_cancer_history == 9.\")\n",
    "\n",
    "# 5) Separate features (X) and target (y)\n",
    "X = df.drop(columns=[\"breast_cancer_history\"])\n",
    "\n",
    "y = df[\"breast_cancer_history\"]\n",
    "\n",
    "# 6) Handle missing values\n",
    "for col in X.columns:\n",
    "    if X[col].isnull().any():\n",
    "        if X[col].dtype in [np.float64, np.int64]:\n",
    "            median_val = X[col].median()\n",
    "            X[col] = X[col].fillna(median_val)\n",
    "            print(f\"Filled missing numeric column '{col}' with median = {median_val}\")\n",
    "        else:\n",
    "            mode_vals = X[col].mode()\n",
    "            fill_val = mode_vals[0] if not mode_vals.empty else \"Unknown\"\n",
    "            X[col] = X[col].fillna(fill_val)\n",
    "            print(f\"Filled missing categorical column '{col}' with mode = {fill_val}\")\n",
    "\n",
    "# 7) Encode categorical features\n",
    "feature_encoders = {}\n",
    "for col in X.select_dtypes(include=[\"object\", \"category\"]).columns:\n",
    "    le = LabelEncoder()\n",
    "    X[col] = le.fit_transform(X[col].astype(str))\n",
    "    feature_encoders[col] = le\n",
    "    print(f\"Encoded '{col}' with classes: {list(le.classes_)}\")\n",
    "\n",
    "# 8) Encode target if needed (likely numeric 0 or 1, so skip if numeric)\n",
    "if y.dtype == 'object' or str(y.dtype).startswith('category'):\n",
    "    target_le = LabelEncoder()\n",
    "    y = target_le.fit_transform(y.astype(str))\n",
    "    print(f\"Encoded target 'breast_cancer_history' with classes: {list(target_le.classes_)}\")\n",
    "else:\n",
    "    target_le = None\n",
    "\n",
    "# 9) Train/Test split\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.20, random_state=42, stratify=y if len(np.unique(y))>1 else None\n",
    ")\n",
    "print(f\"Training shape: {X_train.shape}, Test shape: {X_test.shape}\")\n",
    "\n",
    "# 10) Train XGBoost classifier\n",
    "model = xgb.XGBClassifier(\n",
    "    n_estimators=100,\n",
    "    max_depth=4,\n",
    "    learning_rate=0.1,\n",
    "    subsample=0.8,\n",
    "    colsample_bytree=0.8,\n",
    "    use_label_encoder=False,\n",
    "    eval_metric=\"logloss\",\n",
    "    random_state=42\n",
    ")\n",
    "model.fit(X_train, y_train)\n",
    "print(\"Model training finished.\")\n",
    "\n",
    "# 11) Evaluate\n",
    "y_pred = model.predict(X_test)\n",
    "print(\"Classification Report:\")\n",
    "print(classification_report(y_test, y_pred))\n",
    "try:\n",
    "    y_pred_prob = model.predict_proba(X_test)[:, 1]\n",
    "    auc = roc_auc_score(y_test, y_pred_prob)\n",
    "    print(f\"ROC AUC: {auc:.4f}\")\n",
    "except:\n",
    "    print(\"Could not compute ROC AUC (possible single-class).\")\n",
    "\n",
    "# 12) Ensure data directory exists before saving\n",
    "os.makedirs(DATA_DIR, exist_ok=True)\n",
    "\n",
    "# 13) Save artifacts\n",
    "MODEL_PATH = os.path.join(DATA_DIR, \"bcsc_xgb_model.pkl\")\n",
    "ENCODERS_PATH = os.path.join(DATA_DIR, \"bcsc_feature_encoders.pkl\")\n",
    "joblib.dump(model, MODEL_PATH)\n",
    "print(f\"Saved model to {MODEL_PATH}\")\n",
    "joblib.dump(feature_encoders, ENCODERS_PATH)\n",
    "print(f\"Saved feature encoders to {ENCODERS_PATH}\")\n",
    "\n",
    "if target_le is not None:\n",
    "    TARGET_PATH = os.path.join(DATA_DIR, \"bcsc_target_encoder.pkl\")\n",
    "    joblib.dump(target_le, TARGET_PATH)\n",
    "    print(f\"Saved target encoder to {TARGET_PATH}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "id": "1380a273-669a-412d-ae5b-90e64403b1ec",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "id": "5fcabfca-28c3-4a63-a333-ef8922b49879",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
