# .streamlit/config.toml
[theme]
base               = "light"        # or "dark"
primaryColor       = "#FF6F61"      # Coral
backgroundColor    = "#FFFCF2"      # Cream
secondaryBackgroundColor = "#8FD9A8"  # Mint
textColor          = "#3E3E3E"      # Granite
font               = "sans serif"   # or "serif" / "monospace"
